#构建mysql-mha环境
version: "3.3"
services:
  mysql_master: &mysql_master # 镜像
    image: mysql:5.7
    # 环境变量文件
    env_file:
      - ./env/mysql_master.env
    # 容器名称
    container_name: mysql_master
    # 在容器退出时总是重启
    restart: unless-stopped
    # 端口对外映射
    ports:
      - 3306:3306
    # 数据卷挂载
    volumes:
      # mysql 配置文件
      - ./conf/mysql_master.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      # myqsl 工作目录
      - ./data/master:/var/lib/mysql
      # mysql 数据初始化
      - ./init/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./init/data.sql:/docker-entrypoint-initdb.d/2-data.sql
      # mysql_master 初始化配置
      - ./init/mysql_master.sh:/docker-entrypoint-initdb.d/3-init.sh
    # 容器启动后默认执行的命令
    command: [
        "--server-id=1",
        # "--innodb_flush_log_at_trx_commit=1",
        # "--sync_binlog=1"
      ]

  mysql_slave1:
    # 基础mysql_master的属性
    <<: *mysql_master
    env_file:
      - ./env/mysql_slave.env
    container_name: mysql_slave1
    ports:
      - 33061:3306
    # 启动依赖于 mysql_master
    depends_on:
      - mysql_master
    volumes:
      - ./conf/mysql_slave.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./data/slave1:/var/lib/mysql
      - ./init/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./init/data.sql:/docker-entrypoint-initdb.d/2-data.sql
      # mysql_slave 初始化配置
      - ./init/mysql_slave.sh:/docker-entrypoint-initdb.d/3-init.sh
    command: [
      "--server-id=21",
      "--read_only=1"
    ]

  mysql_slave2:
    <<: *mysql_master
    env_file:
      - ./env/mysql_slave.env
    container_name: mysql_slave2
    ports:
      - 33062:3306
    depends_on:
      - mysql_master
    volumes:
      - ./conf/mysql_slave.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./data/slave2:/var/lib/mysql
      - ./init/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./init/data.sql:/docker-entrypoint-initdb.d/2-data.sql
      - ./init/mysql_slave.sh:/docker-entrypoint-initdb.d/3-init.sh
    command: [
      "--server-id=22",
      "--read_only=1"
    ]
